
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'AmazonSellerCentral'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  raw_database: "edm-saras" #equivalent to project_id in BigQuery, given values is an example name
  raw_schema: "EDM_Daton" #equivalent to dataset in BigQuery, given values is an example name

  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0 # Example- Daton Integration Name: Nike_US_SponsoredBrands --> Position 0, separated by '_'
  default_brandname: "" # Example- default_brandname: "Nike" --> for Single Brand users, with no Brandname in Daton Integration Name

  get_storename_from_tablename_flag: True 
  storename_position_in_tablename: 1 # Example- Daton Integration Name: Nike_US_SponsoredBrands --> Position 1, separated by '_'
  default_storename: "" # Example- default_storename: "US" --> for Single Store users, with no Storename in Daton Integration Name

  currency_conversion_flag: True
  timezone_conversion_flag: True
  to_timezone: 'America/Los_Angeles'

  # Flags to enable/disable models
  AllListingsReport: True
  CatalogItems: True
  FBAAmazonFulfilledShipmentsReport: True
  FBAManageInventory: True
  FBAManageInventoryHealthReport: True
  FBAReturnsReport: True
  FlatFileAllOrdersReportByLastUpdate: True
  FlatFileReturnsReportByReturnDate: True
  InventoryLedgerDetailedReport: True
  ListOrder: True
  ListFinancialEvents: True
  SalesAndTrafficReportByChildASIN: True
  ListingOffersForASIN: True
  SuppressedListingsReport: True
  FlatFileFeedbackReports: True

  # Flags for raw table search patterns and lookback period
  AllListingsReport_tbl_ptrn: '%alllistingsreport'
  AllListingsReport_tbl_exclude_ptrn: ''
  AllListingsReport_lookback: 2592000000

  CatalogItems_tbl_ptrn: '%catalogitems'
  CatalogItems_tbl_exclude_ptrn: ''
  CatalogItems_lookback: 2592000000

  FBAAmazonFulfilledShipmentsReport_tbl_ptrn: '%fulfilledshipments%'
  FBAAmazonFulfilledShipmentsReport_tbl_exclude_ptrn: ''
  FBAAmazonFulfilledShipmentsReport_lookback: 2592000000

  FBAManageInventory_tbl_ptrn: '%fbamanageinventory'
  FBAManageInventory_tbl_exclude_ptrn: ''
  FBAManageInventory_lookback: 2592000000

  FBAManageInventoryHealthReport_tbl_ptrn: '%fbamanageinventoryhealthreport'
  FBAManageInventoryHealthReport_tbl_exclude_ptrn: ''
  FBAManageInventoryHealthReport_lookback: 2592000000

  FBAReturnsReport_tbl_ptrn: '%fbareturnsreport'
  FBAReturnsReport_tbl_exclude_ptrn: ''
  FBAReturnsReport_lookback: 2592000000

  FlatFileAllOrdersReportByLastUpdate_tbl_ptrn: '%flatfileallordersreportbylastupdate'
  FlatFileAllOrdersReportByLastUpdate_tbl_exclude_ptrn: ''
  FlatFileAllOrdersReportByLastUpdate_lookback: 2592000000

  FlatFileReturnsReportByReturnDate_tbl_ptrn: '%flatfilereturnsreportbyreturndate'
  FlatFileReturnsReportByReturnDate_tbl_exclude_ptrn: ''
  FlatFileReturnsReportByReturnDate_lookback: 2592000000

  InventoryLedgerDetailedReport_tbl_ptrn: '%ledgerdetail%'
  InventoryLedgerDetailedReport_tbl_exclude_ptrn: ''
  InventoryLedgerDetailedReport_lookback: 2592000000

  ListFinancialEvents_tbl_ptrn: '%listfinancialevents'
  ListFinancialEvents_tbl_exclude_ptrn: ''
  ListFinancialEvents_lookback: 2592000000

  ListOrder_tbl_ptrn: '%listorder'
  ListOrder_tbl_exclude_ptrn: ''
  ListOrder_lookback: 2592000000

  ListingOffersForASIN_tbl_ptrn: '%listingoffersforasin'
  ListingOffersForASIN_tbl_exclude_ptrn: ''
  ListingOffersForASIN_lookback: 2592000000

  SalesAndTrafficReportByChildASIN_tbl_ptrn: '%salesandtrafficreportbychildasin%'
  SalesAndTrafficReportByChildASIN_tbl_exclude_ptrn: ''
  SalesAndTrafficReportByChildASIN_lookback: 2592000000

  FlatFileFeedbackReports_tbl_ptrn: '%flatfilefeedbackreport%'
  FlatFileFeedbackReports_tbl_exclude_ptrn: ''
  FlatFileFeedbackReports_lookback: 2592000000

  SuppressedListingsReport_tbl_ptrn: '%suppressedlistingsreport%'
  SuppressedListingsReport_tbl_exclude_ptrn: ''
  SuppressedListingsReport_lookback: 2592000000

  # Variables used for dbt-tests
  'dbt_date:time_zone': 'America/Los_Angeles'
  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  AmazonSellerCentral:
    AmazonSellerCentral:
      +schema: stg_amazon_sellercentral
