
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'AmazonSellerCentral'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  raw_database: "edm-saras" #equivalent to project_id in BigQuery
    # Example Database name
  raw_schema: "EDM_Daton" #equivalent to dataset in BigQuery
    # Example Schema name

  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0
    # Example- Daton Integration Name: Nike_US_SponsoredBrands --> Position 0, separated by '_'
  default_brandname: "" 
    # Example- default_brandname: "Nike" --> for Single Brand users, with no Brandname in Daton Integration Name

  get_storename_from_tablename_flag: True 
  storename_position_in_tablename: 1
    # Example- Daton Integration Name: Nike_US_SponsoredBrands --> Position 1, separated by '_'
  default_storename: "" 
    # Example- default_storename: "US" --> for Single Store users, with no Storename in Daton Integration Name

  # Variables used for dbt-tests
  'dbt_date:time_zone': 'America/Los_Angeles'
  to_timezone: 'America/Los_Angeles'


  currency_conversion_flag: False
  timezone_conversion_flag: False
  raw_table_timezone_offset_hours: {
    "Amazon.SellerCentral.Brand_UK_AmazonSellerCentral_FlatFileAllOrdersReportbyLastUpdate":-7,
    "Amazon.SellerCentral.Brand_UK_AmazonSellerCentral_ListOrder":-7,
    "Amazon.SellerCentral.Brand_UK_AmazonSellerCentral_FBAAmazonFulfilledShipmentsReport":-7,
    "Amazon.SellerCentral.Brand_UK_AmazonSellerCentral_InventoryLedgerDetailedReport":-7
    }
      # Above are Example entries for raw table level input offset hours

  AllListingsReport: True
  CatalogItems: True
  FBAAmazonFulfilledShipmentsReport: True
  FBAManageInventory: True
  FBAManageInventoryHealthReport: True
  FBAReturnsReport: True
  FlatFileAllOrdersReportByLastUpdate: True
  FlatFileReturnsReportByReturnDate: True
  InventoryLedgerDetailedReport: True
  ListOrder: True
  ListFinancialEventsOrderFees: True
  ListFinancialEventsServiceFees: True
  ListFinancialEventsOrderPromotions: True
  ListFinancialEventsOrderRevenue: True
  ListFinancialEventsOrderTaxes: True
  ListFinancialEventsRefundFees: True
  ListFinancialEventsRefundPromotions: True
  ListFinancialEventsRefundRevenue: True
  ListFinancialEventsRefundTaxes: True
  SalesAndTrafficReportByChildASIN: True
  ListingOffersForASIN: True


  AllListingsReport_tbl_ptrn: '%alllistingsreport'
  AllListingsReport_tbl_exclude_ptrn: ''
  AllListingsReport_lookback: 2592000000
  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  AmazonSellerCentral:
    AmazonSellerCentral:
      +schema: stg_amazon_sellercentral
